---
- name: gather facts
  yysetup:

- name: install common packages debian/ubuntu
  apt: pkg={{ item }} state=latest update_cache=yes
  with_items:
    - build-essential
    - git
    - python-dev
    - libpq-dev
  when: ansible_os_family == "Debian"

- name: set hostname file
  template: src=hostname dest=/etc/hostname owner=root group=root mode=644

- name: set hostname
  command: hostname {{pri_group_id}}-{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] | ip_slice }}
